import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Link from "next/link";

// ? image
import brand from "../../public/img/web/brand.png";
import img1 from "../../public/img/web/img1.png";
import img2 from "../../public/img/web/img2.png";
import img3 from "../../public/img/web/img3.png";
import ellipse from "../../public/img/web/ellipse_patern.svg";
import float1 from "../../public/img/web/img1_float.png";

export default function signUp() {
  return (
    <div>
      <Head>
        <title>Periksa Doc | Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/web/logo.png" />
      </Head>
      <div className="w-screen bg-[#BED7ED]">
        <form action="" method="post">
          <div className="grid grid-cols-2 place-content-center">
            <div className="flex">
              <div className="my-auto">
                <Image src={img1} style={{ width: "100%" }} alt="image" />
              </div>
            </div>
            <div
              className="bg-white rounded-l-3xl p-8 flex flex-col"
              style={{ minHeight: "100vh" }}
            >
              <div className="my-auto">
                <div className="mb-14 text-gray-800">
                  <h3 className="text-4xl font-bold mb-1">Sign Up</h3>
                </div>
                <div className="grid grid-cols-2 mb-3 gap-3">
                  <div>
                    <input
                      type="text"
                      name=""
                      id=""
                      placeholder="First Name"
                      required
                      className="w-full p-3 border border-gray-500 outline-[#1480eb] rounded-md delay-100"
                    />
                  </div>
                  <div>
                    <input
                      type="text"
                      name=""
                      id=""
                      placeholder="Last Name"
                      required
                      className="w-full p-3 border border-gray-500 outline-[#1480eb] rounded-md delay-100"
                    />
                  </div>
                </div>
                <div className="mb-3">
                  <input
                    type="text"
                    name=""
                    id=""
                    required
                    placeholder="Email Address"
                    className="w-full p-3 border border-gray-500 outline-[#1480eb] rounded-md delay-100"
                  />
                </div>
                <div className="mb-3">
                  <input
                    type="text"
                    name=""
                    id=""
                    required
                    placeholder="Phone Number"
                    className="w-full p-3 border border-gray-500 outline-[#1480eb] rounded-md delay-100"
                  />
                </div>
                <div className="grid grid-cols-2 mb-3 gap-3">
                  <div>
                    <input
                      type="password"
                      name="password"
                      id="password"
                      required
                      placeholder="Password"
                      className="w-full p-3 border border-gray-500 outline-[#1480eb] rounded-md delay-100"
                    />
                  </div>
                  <div>
                    <input
                      type="password"
                      name="repeat_password"
                      id="repeat_password"
                      required
                      placeholder="Repeat Password"
                      className="w-full p-3 border border-gray-500 outline-[#1480eb] rounded-md delay-100"
                    />
                  </div>
                </div>
                <div className="mb-3 grid">
                  <button
                    type="submit"
                    className="btn btn-primary-alt font-medium"
                  >
                    Sign Up
                  </button>
                </div>
                <div className="mb-3">
                  <span className="block text-gray-500 text-center">
                    Sudah punya akun?
                  </span>
                  <Link href="/login">
                    <a className="text-[#1480eb] text-center block hover:underline">
                      Login
                    </a>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
